Enable unstable features when editing in VS Code
zcash/librustzcash pull request #1077
Opened 2023-12-29 17:16 UTC by AArnott

This improves the editing experience by 'enabling' all the code that otherwise is turned off because of the `unstable` flag.

2024-01-02 18:59 UTC, nuttycom reviewed
In general we don't commit editor-specific config to this respository. I'm not strongly opposed to it in this case, but maybe @str4d or another vscode user can chime in here.

2024-01-03 03:54 UTC, AArnott commented
It took me a while to figure out how to get a good editing experience by adding this file. As it doesn't hurt any _other_ IDE to add it, IMO we should add it so that any VS Code user doesn't have to independently discover how to do it, and maintain a file like this without checking it in by accident.
Either way, it's not blocking me. It's in my own fork of the repo where I do most of my work.

2024-01-03 17:26 UTC, str4d requested changes
I'm fine with including this in the repo to help VS Code users, but we shouldn't special-case the `unstable` flag; there are other flags that are also relevant.

2024-01-03 17:26 UTC, str4d commented on .vscode/settings.json
> +    "rust-analyzer.cargo.features": ["unstable"]
I develop locally with:
```suggestion
    "rust-analyzer.cargo.features": "all"
```

2024-01-04 21:19 UTC, str4d approved these changes
ACK (haven't tested this PR but I have the identical setting locally)

2024-01-04 21:19 UTC, merged