Doc improvements
zcash/librustzcash pull request #1103
Opened 2024-01-07 03:29 UTC by AArnott

2024-01-18 22:14 UTC, str4d requested changes

2024-01-18 22:14 UTC, str4d commented on zcash_primitives/src/transaction/fees/zip317.rs
> +/// An error will be returned if a coin containing a non-p2pkh script is provided as an input.
```suggestion
/// This fee rule supports Orchard, Sapling, and (P2PKH only) transparent inputs.
/// Returns an error if a coin containing a non-p2pkh script is provided as an input.
```

2024-01-18 22:14 UTC, str4d commented on zcash_keys/src/encoding.rs
>  pub trait AddressCodec<P>
I'm happy to merge the PR with these docs, but this trait is almost certainly going away (as the address encoding and decoding logic here is duplicative of `zcash_address`).

2024-01-19 19:16 UTC, nuttycom approved these changes
ACK, doc-only.

2024-01-23 16:19 UTC, str4d approved these changes
ACK 296e770ec827c9a500e6751f681e1d79371734a9

2024-01-23 16:19 UTC, merged