Sqlite wallet/fix multi pool checkpointing
zcash/librustzcash pull request #1262
Opened 2024-03-12 19:15 UTC by nuttycom

2024-03-12 22:22 UTC, str4d requested changes
Flushing review comments as of e1c0f257d52fa2d8cd3a7ee10dc6bd434419eac2

2024-03-12 23:57 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/librustzcash/compare/e1c0f257d52fa2d8cd3a7ee10dc6bd434419eac2..ae3f56da1fac1be04134ed433a551b9ca0e5eb63) to address comments from code review & disable tests that require test framework changes.

2024-03-13 00:16 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/librustzcash/compare/47866a757cc647f95d2a975b825f9a7b05e01ec2..fb46ff999f06ffdcead19efc1586dd129d124c9d) to rebase on `main`

2024-03-13 01:00 UTC, str4d approved these changes
utACK a0460886f4ad1ab3503517e601614e575f697c10

2024-03-13 01:01 UTC, nuttycom commented on zcash_client_sqlite/src/lib.rs
> +                    I: Iterator<Item = &'a BlockHeight>,
I fooled around with a couple of things and couldn't get it to work, so went with the simple thing. :)

2024-03-13 01:01 UTC, merged

2024-03-17 15:14 UTC, AArnott commented
Missing a CHANGELOG addition for this? Ideally it would include not just the changed APIs, but a brief explanation of how to come up with the new `ChainState` argument that these APIs now require.

2024-03-17 15:20 UTC, nuttycom commented
> Missing a CHANGELOG addition for this? Ideally it would include not just the changed APIs, but a brief explanation of how to come up with the new `ChainState` argument that these APIs now require.

@AArnott thanks for noticing, I'll fix this up. The conversion you want is https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/proto.rs#L297-L307