Update bip0039 for Arti support in Zebra
zcash/librustzcash pull request #1377
Opened 2024-04-27 06:28 UTC by emersonian

Upgrading bip0039 to v0.12 in zcash_primitives resolves Zebra's ability to build with Arti (Tor) support.

Patch versions will need to be released of the following crates to simplify integration with Zebra:

- zcash_primitives: v0.13.1
- zcash_client_backend: v0.10.1 (depending upon zcash_primitives v0.13.1)
- zcash_proofs: v0.13.1 (depending upon zcash_primitives v0.13.1)
- zcash_script: v0.1.16 (depending upon zcash_primitives v0.13.1)

[Demonstration of a working build](https://github.com/emersonian/zebra/tree/arti-deps)

See ZcashFoundation/zebra#8328

2024-04-29 14:35 UTC, str4d requested changes
NACK for the same reason as when this was proposed in #1261.

We attempted to upgrade from `bip0039 0.10` in #808, but had to downgrade in #812 because the change in `bip0039 0.11` to use generics resulted in me spending several hours fighting and losing to the C++ template system in `zcashd`.

While `zcashd` depends on `bip0039 0.10` via `zcash_primitives::zip339`, we will not be upgrading this dependency. If someone else wants to fight the C++ template system to enable this, let me know!

2024-04-29 14:35 UTC, str4d commented
Also, as a side-note:

> Patch versions will need to be released

As documented in the `Cargo.toml` that you edited, `bip0039` is exposed in our API, and thus changing its left-most non-negative version integer is a SemVer-breaking change in Rust.

2024-05-07 15:12 UTC, nuttycom commented
@str4d `zip339` is simply a reexport of the `bip0039` crate, and nothing in `librustzcash` depends upon it. Also, given the extraction of `zcash_keys`, I don't think that it's appropriate for this to live in `zcash_primitives` any longer anyway. I recommend that we simply remove the `zip339` module entirely, which then decouples the use of `bip0039` in `zcashd` from any potential use in `zebra`.

2024-05-07 23:20 UTC, nuttycom commented
@emersonian instead of this, please just revert https://github.com/zcash/librustzcash/pull/424 instead. This will require a major version bump to `zcash_primitives` and downstream crates, so make sure to note the `zip339` module as removed in the CHANGELOG so that we remember that a major version bump is required.

2024-05-14 09:41 UTC, closed without merging

2024-05-14 09:42 UTC, daira commented
Superceded by #1391.