zcash_client_sqlite: Fix handling of PRAGMA directives.
zcash/librustzcash pull request #1433
Opened 2024-06-19 21:17 UTC by nuttycom

The `foreign_keys` pragma has no effect when used within a transaction, so it should only be set at the top level. The `legacy_alter_table` pragma should only be used in cases where its effect is explicitly intended.

Best reviewed hiding whitespace changes.

2024-06-19 22:35 UTC, str4d requested changes
Reviewed a452cf966972339cc042906a53897607fb6ef163.

2024-06-19 22:35 UTC, str4d commented on zcash_client_sqlite/src/wallet/init.rs
> +        for (actual, expected) in rows.iter().zip(expected_tables.iter()) {
`zip` short-circuits, so we no longer detect whether the real database contains tables that aren't listed in `expected_tables`. I also note that we weren't detecting the reverse case previously (`expected_tables` containing tables that are not in the real database).

Simple fix is to add an assertion that the two are the same length, prior to the `zip`:
```suggestion
        assert_eq!(rows.len(), expected_tables.len());
        for (actual, expected) in rows.iter().zip(expected_tables.iter()) {
```

2024-06-19 22:35 UTC, str4d commented on zcash_client_sqlite/src/wallet/init/migrations.rs
> +    pub(crate) fn test_migrate(migrations: &[Uuid]) {
```suggestion
    /// Tests that we can migrate from a completely empty wallet database to the target
    /// migrations.
    pub(crate) fn test_migrate(migrations: &[Uuid]) {
```

2024-06-19 22:35 UTC, str4d commented on zcash_client_sqlite/src/wallet/init.rs
> +pub(crate) fn init_wallet_db_internal<P: consensus::Parameters + 'static>(
AFAICT this is unnecessary; the new places we use this are all in sub-modules. So to ensure we don't use this elsewhere in the crate, undo this:
```suggestion
fn init_wallet_db_internal<P: consensus::Parameters + 'static>(
```

2024-06-19 22:51 UTC, str4d approved these changes
utACK 1110f5d8fb22650e2f0e10300be2ce62d8036d78

2024-06-19 23:56 UTC, merged

2024-06-20 00:03 UTC, daira commented on zcash_client_sqlite/src/wallet/init.rs
>      adapter.init().expect("Migrations table setup succeeds.");
Pre-existing issue, but the `?` early returns on lines 289 and 292 can bypass resetting `PRAGMA foreign_keys = ON`, leaving the database in a less-safe state.

2024-06-20 00:07 UTC, daira reviewed
Post-hoc ACK with comment about a pre-existing issue.