[ZIP-233] Network Sustainability Mechanism: Burning
zcash/librustzcash pull request #1567
Opened 2024-10-11 11:07 UTC by giddie

This mostly consists of the addition of a `burn_amount` transaction field, introduced in the `ZFuture` network upgrade. Enabling `cfg(zcash_unstable = "zfuture")` meant that a lot of TZE code was unnecessarily enabled, so we switched some of those sections to `zcash_unstable = "tze"` as well as introducing `zcash_unstable = "nsm"` to keep things separate. The `zfuture` cfg is now used just to enable the ZFuture network upgrade.

The code for the generated test vectors is available in [this PR](https://github.com/zcash/zcash-test-vectors/pull/101).

2025-02-07 18:31 UTC, daira commented on components/zcash_protocol/src/consensus.rs
> +    NetworkUpgrade::ZFuture,
This change is incorrect I believe. `ZFuture` by definition has no activation height.

2025-02-07 18:32 UTC, daira requested changes
Blocking on review by @str4d and @nuttycom, since this requires a design decision about the future of `ZFuture`.

2025-02-26 19:05 UTC, shielded-nate commented on components/zcash_protocol/src/consensus.rs
> +    NetworkUpgrade::ZFuture,
What's the recommended development pattern for naming and activating "provisional" protocol changes within dev branches prior to those changes being accepted or planned for any network upgrade?

In other words, what's the best way to do steps 2 and 3 below (wrt `librustzcash` crates):

1. Implement some consensus protocol change,
2. Name the new protocol version (with a provisional dev-branch-specific identifier),
3. Modify update/activation logic and tests for activating that new protocol change,
4. Later, if things go well, after ZIPs are specified and the changes are slated for a real life upgrade, submit another code change to rename the provisional protocol version with the real target version,
5. Merge the protocol changes with other protocol changes for the slated upgrade, etc...

Also, I believe this process/convention needs to be shared somewhat with `zebra`, correct?

2025-02-26 19:09 UTC, shielded-nate commented on components/zcash_protocol/src/consensus.rs
> +    NetworkUpgrade::ZFuture,
I realized my question isn't directly relevant to this diff hunk, and I understand why `::Future` should not be added to that list.

2025-02-26 19:13 UTC, nuttycom commented on components/zcash_protocol/src/consensus.rs
> +    NetworkUpgrade::ZFuture,
As discussed in the last Arborist call, the proposed mechanism is to guard those changes with:

```
#[cfg(all(zcash_unstable = "nu7", feature = "zip-233"))]
```

This requires the `zcash_unstable` feature flag to be set, and also for an ordinary additive Rust feature flag. This will make it so that the code cannot be part of any ordinary build, but those who need to experiment with and ensure build consistency can proceed.

As part of this, we should add a `NetworkUpgrade::Nu7` constant that is guarded by `#[cfg(zcash_unstable = "nu7")]`

2025-02-26 19:25 UTC, nuttycom commented on components/zcash_protocol/src/consensus.rs
> +    NetworkUpgrade::ZFuture,
I'll make a PR to `zcash_protocol` that adds these constants.

2025-02-26 20:22 UTC, nuttycom commented on components/zcash_protocol/src/consensus.rs
> +    NetworkUpgrade::ZFuture,
https://github.com/zcash/librustzcash/pull/1718

2025-04-30 14:34 UTC, aphelionz commented
Can somebody re-run the clippy test when it's convenient? 🙏

2025-04-30 17:12 UTC, nuttycom commented
@aphelionz there's an underlying clippy CI issue being fixed in https://github.com/zcash/librustzcash/pull/1785 - you might want to rebase once that merges to clear this issue.

2025-05-01 14:48 UTC, aphelionz commented
@mariopil are you able to quickly rebase one more time now that the clippy fixes are in?

2025-05-01 15:33 UTC, nuttycom requested changes
A few high-level blocking comments thus far.

2025-05-01 15:33 UTC, nuttycom commented on components/zcash_protocol/src/consensus.rs
> +            BranchId::Nu7 => 0x7719_0ad8,
This value is not yet established by a deployment ZIP, and so MUST NOT be set to any non-0xffff_ffff value.
```suggestion
            BranchId::Nu7 => 0xffff_ffff,
```

2025-05-01 15:33 UTC, nuttycom commented on components/zcash_protocol/src/consensus.rs
> +            0x77190ad8 => Ok(BranchId::Nu7),
This value is not yet established by a deployment ZIP, and so MUST NOT be set to any non-0xffff_ffff value.
```suggestion
            0xffff_ffff => Ok(BranchId::Nu7),
```

2025-05-01 15:33 UTC, nuttycom commented on components/zcash_protocol/src/consensus.rs
>          );
This code doesn't make sense; I don't know why it was like this to begin with.
```suggestion
```

2025-05-01 15:33 UTC, nuttycom commented on zcash_primitives/src/transaction/builder.rs
> +    zip233_amount: Option<Zatoshis>,
This field should not be optional; it should be set to zero instead of None in order to avoid there being multiple representations of the zero value.

2025-05-13 13:19 UTC, mariopil commented
@aphelionz I was on vacation last two week - I've rebased now vs latest main and addressed @nuttycom comments.

2025-06-08 16:08 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +            TxVersion::V6 => Ok(Self::from_data_v5(data)),
If this just happens to be the same as v5, I would suggest still making a `from_data_v6` method and having it call `from_data_v5`. As it is, it bakes the assumption that v5 and v6 are the same in this respect into callers. (I know that this is a private method and there aren't many callers, but still.)

2025-06-08 16:15 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +            TxVersion::ZFuture => Self::read_v5(&mut reader.into_base_reader(), version),
Non-blocking for this PR, but I don't see the point in retaining `ZFuture` as a snapshot of something based on v5 that will never be implemented in that form. It should be based on v6 or stripped out.

2025-06-08 16:30 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +        let orchard_bundle = orchard_serialization::read_v5_bundle(&mut reader)?;
The Orchard bundle will not be the same in v6, because of action groups. Add a `read_v6_bundle` method.

2025-06-08 16:34 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +        let zip233_amount = if version == TxVersion::V6 {
This should not be conditional on `version == TxVersion::V6`, because this method is by definition for the v6 format. (Also if it were reused for v7, say, this would be wrong.)

2025-06-08 16:35 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
>          #[cfg(zcash_unstable = "zfuture")]
I suggest deciding whether ZFuture is based on v5 or v6 and only including it in that method, rather than including it in both (resulting in dead code).

2025-06-08 16:36 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +        #[cfg(zcash_unstable = "zfuture")]
See comment above; include TZE support either in v5 or v6, not both.

2025-06-08 16:39 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +        orchard_serialization::write_v5_bundle(self.orchard_bundle.as_ref(), &mut writer)?;
See above; this must be `write_v6_bundle`.

2025-06-08 16:44 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +        writer.write_u64_le(self.zip233_amount.into())?;
This field is in the wrong place according to ZIP 230.

2025-06-08 16:50 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +    #[cfg(all(not(zcash_unstable = "zfuture"), not(feature = "zip-233")))]
Can this and the subsequent definitions not be merged? The conditionality seems to be regular and should not require repeating this much code.

2025-06-08 16:57 UTC, daira commented on zcash_primitives/src/transaction/sighash.rs
> +        TxVersion::V6 => v5_signature_hash(tx, signable_input, txid_parts),
Since this will be different, add `v6_signature_hash` and have it call `v5_signature_hash` in this PR.

2025-06-08 17:00 UTC, daira commented on zcash_primitives/src/transaction/tests.rs
> +    if tx.version == TxVersion::V6 {
```suggestion
    if tx.version >= TxVersion::V6 {
```

2025-06-08 17:02 UTC, daira commented on zcash_primitives/src/transaction/mod.rs
> +    zip233_amount: Zatoshis,
Consider moving this to just after `expiry_height`, so the the argument order matches the order of encoding in ZIP 230.

2025-06-08 17:05 UTC, daira commented on zcash_primitives/src/transaction/tests/data.rs
I did not review changes in this file.

2025-06-08 17:06 UTC, daira requested changes
Changes needed.

2025-06-09 14:18 UTC, mariopil commented
Thank you @daira for the review. I've done the fixes. I've added `read_v6_header_fragment` and `write_v6_header`, and moved the reading and writing of `zip233_amount` there.

2025-06-09 14:22 UTC, mariopil commented on zcash_primitives/src/transaction/mod.rs
> +    #[cfg(all(not(zcash_unstable = "zfuture"), not(feature = "zip-233")))]
The `arb_txdata` functions are inside the `prop_compose!` macro. Moving the `cfg` conditions inside it causes compilation errors.

2025-06-09 22:30 UTC, daira commented on zcash_primitives/src/transaction/tests.rs
> +            v5_signature_hash(&txdata, &SignableInput::Shielded, &txid_parts).as_ref(),
```suggestion
            v6_signature_hash(&txdata, &SignableInput::Shielded, &txid_parts).as_ref(),
```
(I think.)

2025-06-09 22:41 UTC, daira commented on zcash_primitives/src/transaction/tests/data.rs
> +                zip233_amount: 1291391780532887,
156075263189478 + 761218910752131 + 337114183642658 + 1291391780532887 = 2545800138117154
 which exceeds `MAX_MONEY` = 2100000000000000. This is therefore not a valid test, even if it passes for the current code.

2025-06-10 10:56 UTC, mariopil commented on zcash_primitives/src/transaction/tests/data.rs
> +                zip233_amount: 1291391780532887,
It's fixed now.

2025-06-13 19:52 UTC, daira commented
MarioP wrote in #zebra on the R&D Discord:
> I've noticed this digest header change https://github.com/zcash/librustzcash/blob/2630263f31540c7b89d64dc4c74dbaa736e14a9f/zcash_primitives/src/transaction/txid.rs#L240
> in the [ZIP-233 librustzcash PR](https://github.com/zcash/librustzcash/pull/1567) breaks a few tests in Zebra (`merkle_root_is_valid`, `v5_with_sapling_spends`, `v4_with_sapling_spends`, `block_test_vectors`, `binding_signatures`) that test processing old blocks from testnet and mainnet. Shouldn't the writing `zip233Amount` in the header be conditioned e.g. based on the Tx version?

Yes, probably, although I haven't had chance to look in detail. Please check that this does not break Zebra tests before merging.

2025-06-16 09:01 UTC, mariopil commented
Thank you, @daira. Yes, I've tested this with Zebra, and all tests are passing.

2025-06-30 13:02 UTC, aphelionz commented
@daira @nuttycom friendly reminder to review again 🙏

2025-07-14 21:28 UTC, arya2 reviewed
This is looking good, there are a handful of outstanding lints and compilation issues that need fixing.

2025-07-14 21:28 UTC, arya2 commented on zcash_client_sqlite/Cargo.toml
I don't see this in the diff on Github somehow, but it seems an import for `zcash_protocol::value::Zatoshis` was added in `zcash_client_sqlite/src/lib.rs` that is only used when compiling for tests, or with the `test-dependencies`, `transparent-inputs`, or `unstable` features enabled. The import can be hidden behind `#[cfg(any(test, feature = "transparent-inputs", feature = "unstable", feature = "test-dependencies"))]` to resolve the lint, or the type can be referenced with qualifiers instead.

The import also seems to be missing a `Zatoshis` import in `zcash_client_sqlite/src/testing/db.rs` used by the `Delegate` derive macro.

There are also a few other lints that clippy complains about when compiling with all features (run `cargo clippy --all-features` to reproduce).

There also seems to be a compilation issue when running `RUSTFLAGS='--cfg zcash_unstable="nu7"' cargo test --release --all-features` that could be fixed by adding:

```rust
            #[cfg(all(zcash_unstable = "nu7", feature = "zip-233"))]
            Zatoshis::ZERO,
```

on line 427 of `zcash_client_sqlite/src/wallet/init/migrations.rs`.

There may be other lints or compilation issues to resolve with various combinations of feature flags and compilation configs.

2025-07-14 21:28 UTC, arya2 commented on zcash_primitives/src/transaction/mod.rs
> +        orchard_serialization::write_v5_bundle(self.orchard_bundle.as_ref(), &mut writer)?;
Fixed [here](https://github.com/zcash/librustzcash/pull/1567/commits/b1b5499d088ce398d8526b0ed806634082567106#diff-f959b90cdede132f173c5c1451526912ee12a4c91fc76c2bd9074f970e107ffdR985) in https://github.com/zcash/librustzcash/pull/1567/commits/b1b5499d088ce398d8526b0ed806634082567106.

2025-07-14 21:28 UTC, arya2 commented on zcash_primitives/src/transaction/tests.rs
> +            v5_signature_hash(&txdata, &SignableInput::Shielded, &txid_parts).as_ref(),
Fixed [here](https://github.com/zcash/librustzcash/pull/1567/commits/b1b5499d088ce398d8526b0ed806634082567106#diff-5b013fe12bd357fb3da5178005a4fc97b651f05d3fafb6174533c23dc4dcfe98R458) in https://github.com/zcash/librustzcash/pull/1567/commits/b1b5499d088ce398d8526b0ed806634082567106.

Verified that the test transactions used here are all v6, so it's correct to use `v6_signature_hash()`.

2025-07-14 21:28 UTC, arya2 commented on zcash_primitives/src/transaction/tests/data.rs
> +                zip233_amount: 1291391780532887,
The sum of the new values [here](https://github.com/zcash/librustzcash/pull/1567/commits/b1b5499d088ce398d8526b0ed806634082567106#diff-d0dad6fb850fed6e31956355401deeb7a6fba56197dc7055ba5883145fbdfa41R7640-R7641) are exactly equal to max money. This should be valid for that single transaction, but may make the transaction invalid in most contexts. If it's not intended to test that amounts summing to exactly MAX_MONEY will work, I would suggest using smaller amounts.

2025-07-15 08:09 UTC, mariopil commented on zcash_primitives/src/transaction/tests/data.rs
> +                zip233_amount: 1291391780532887,
Those values were generated randomly by one of the zcash_test_vectors script. All the transaction inputs in the scripts are generated randomly in the range 0 to MAX_MONEY, so in an extreme case it is possible to have the sum greater than MAX_MONEY - I've added a condition to limit that to the MAX_MONEY in such an extreme case. Here, it was only a one case with such high values.

2025-07-15 09:38 UTC, mariopil commented on zcash_client_sqlite/Cargo.toml
Thank you for the hints. I've fixed those issues now.

2025-07-15 18:26 UTC, daira commented on pczt/src/roles/tx_extractor/mod.rs
> +            Zatoshis::ZERO,
```suggestion
            Zatoshis::ZERO, // TODO: change when PCZTs add v6 transaction support
```

2025-07-21 18:41 UTC, nuttycom commented
https://github.com/zcash/librustzcash/pull/1879 now builds atop this branch, merging `main` and addressing comments from review.

2025-08-06 12:28 UTC, merged