Implement F4Jumble
zcash/librustzcash pull request #383
Opened 2021-05-18 02:17 UTC by nuttycom

Fixes #378

2021-05-18 23:05 UTC, str4d requested changes

2021-05-18 23:05 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +use std::cmp::min;
```suggestion
use std::cmp::min;
use std::ops::RangeInclusive;

const VALID_LENGTH: RangeInclusive<usize> = 48..=16448;
```

2021-05-18 23:05 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +pub fn f4jumble(mut a: Vec<u8>) -> Option<Vec<u8>> {
```suggestion
pub fn f4jumble(a: &[u8]) -> Option<Vec<u8>> {
```

2021-05-18 23:05 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +pub fn f4jumble_inv(mut c: Vec<u8>) -> Option<Vec<u8>> {
```suggestion
pub fn f4jumble_inv(c: &[u8]) -> Option<Vec<u8>> {
```

2021-05-18 23:05 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +            let jumbled = f4jumble(msg.clone()).unwrap();
```suggestion
            let jumbled = f4jumble(&msg).unwrap();
```

2021-05-18 23:05 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +            let unjumbled = f4jumble_inv(jumbled).unwrap();
```suggestion
            let unjumbled = f4jumble_inv(&jumbled).unwrap();
```

2021-05-18 23:06 UTC, str4d commented
ALso, add tests that run this against the test vectors from https://github.com/zcash-hackworks/zcash-test-vectors/pull/31 (once that PR is merged).

2021-05-18 23:17 UTC, nuttycom commented on zcash_primitives/src/address/f4jumble.rs
> +        result.into_iter().take(self.l_r).collect()
I tried everything to get this to be a flat_map, I'll have to see if this compiles.

2021-05-18 23:24 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +        result.into_iter().take(self.l_r).collect()
As long as the output can be moved it should be fine; `.to_vec().into_iter()` should achieve this.

2021-05-20 13:16 UTC, str4d approved these changes
utACK with @daira and @therealyingtong.

2021-05-20 13:16 UTC, str4d commented on zcash_primitives/src/address/f4jumble.rs
> +            assert_eq!(jumbled, v.jumbled);
Also test the other direction:
```suggestion
            let jumbled = f4jumble(&v.normal).unwrap();
            assert_eq!(jumbled, v.jumbled);
            let unjumbled = f4jumble_inv(&v.jumbled).unwrap();
            assert_eq!(unjumbled, v.normal);
```

2021-05-20 13:53 UTC, merged