Make CompactSize serialization functions public.
zcash/librustzcash pull request #428
Opened 2021-08-18 14:08 UTC by nuttycom

2021-08-30 18:53 UTC, daira commented on components/zcash_encoding/Cargo.toml
> +description = "Binary encodings of types used througout the Zcash ecosystem."
```suggestion
description = "Binary encodings of types used throughout the Zcash ecosystem."
```

2021-08-30 18:56 UTC, daira approved these changes
utACK modulo remaining clippy lints.

2021-08-31 20:01 UTC, str4d requested changes
LGTM overall.

2021-08-31 20:01 UTC, str4d commented on components/zcash_encoding/README.md
> +Zcash ecosystem.
```suggestion
This library provides common encoding and decoding operations for stable binary
encodings used throughout the Zcash ecosystem.
```

2021-09-01 19:41 UTC, str4d commented on components/zcash_encoding/src/lib.rs
> +/// 0x0..=0x02000000
```suggestion
/// Namespace for functions for compact encoding of integers.
///
/// This codec requires integers to be in the range `0x0..=0x02000000`, for compatibility
/// with Zcash consensus rules.
```

2021-09-01 19:41 UTC, str4d commented on components/zcash_encoding/src/lib.rs
> +    /// Read an integer encoded in compact form.
```suggestion
    /// Reads an integer encoded in compact form.
```

2021-09-01 19:41 UTC, str4d commented on components/zcash_encoding/src/lib.rs
> +/// each element of the vector.
```suggestion
/// Namespace for functions that perform encoding of vectors.
///
/// The length of a vector is restricted to at most `0x02000000`, for compatibility with
/// the Zcash consensus rules.
```

2021-09-01 19:41 UTC, str4d commented on components/zcash_encoding/src/lib.rs
> +    /// Writes a slice of values by writing CompactSize-encoded integer specifying the length of
```suggestion
    /// Writes a slice of values by writing [`CompactSize`]-encoded integer specifying the length of
```

2021-09-01 19:41 UTC, str4d commented on components/zcash_encoding/src/lib.rs
> +/// length must be statically known or obtained from other parts of the input stream.
```suggestion
/// Namespace for functions that perform encoding of array contents.
///
/// This is similar to the [`Vector`] encoding except that no length information is
/// written as part of the encoding, so length must be statically known or obtained from
/// other parts of the input stream.
```

2021-09-01 19:41 UTC, str4d commented on zcash_primitives/src/transaction/components/tze.rs
> -
Slight misunderstanding of my previous comment: by our existing convention, `use byteorder` would be grouped with `use zcash_encoding`.

2021-09-01 19:45 UTC, merged