Add utilities for incremental merkle tree serialization.
zcash/librustzcash pull request #522
Opened 2022-03-10 20:35 UTC by nuttycom

2022-03-11 19:57 UTC, str4d requested changes

2022-03-11 19:57 UTC, str4d commented on components/zcash_encoding/src/lib.rs
> +    /// able to be correctly decoded as a vector.
I do not like this as an API on `Vector`. My concern is not as much with not enough items being available (returning an error in this case is functionally equivalent to if the writing of an individual item failed; the IO process abruptly halts), but with too many items being available (and `items_to_write` being incorrectly set).

I would prefer a bound `I: Iterator<Item = E> + ExactSizeIterator`; then we remove the `items_to_write` parameter (instead using `items.len()`). Then if the caller explicitly wants to truncate their source of items, they can use `.take(items_to_write)` on the iterator passed in.

2022-03-12 00:15 UTC, nuttycom commented on components/zcash_encoding/src/lib.rs
>          vec.iter().try_for_each(|e| func(&mut writer, e))
I tried this, and that iterator doesn't implement `ExactSizeIterator`.

2022-03-12 00:30 UTC, str4d approved these changes
utACK abd63166c0ca11763cfaf8f0a79fb2cf2e35f765

2022-03-12 00:54 UTC, merged