Correctly construct outputs when spending internal notes.
zcash/librustzcash pull request #688
Opened 2022-10-31 21:49 UTC by nuttycom

This builds atop #658

2022-11-01 04:38 UTC, str4d requested changes
Reviewed f3f31dab1cea2a3490e02001c5461737f52095f1.

2022-11-01 04:38 UTC, str4d commented on zcash_client_backend/src/data_api/wallet.rs
> +        // diversifier index for creating a change address.
I agree that this shouldn't occur in general (for wallets following ZIP 316), but I'd prefer if we could check internal vs external reliably. And I've thought of a hacky way to do it 🙂
```rust
let note = {
    let external_note = dfvk.fvk()
        .vk
        .to_payment_address(selected.diversifier)
        .unwrap()
        .create_note(selected.note_value.into(), selected.rseed);
    let internal_note = dfvk.internal()
        .fvk()
        .vk
        .to_payment_address(selected.diversifier)
        .unwrap()
        .create_note(selected.note_value.into(), selected.rseed);

    let expected_root = selected.witness.root();
    if expected_root == merkle_path.root(external_note.cmu()) {
        Ok(external_note)
    else if expected_root == merkle_path.root(internal_note.cmu()) {
        Ok(internal_note)
    } else {
        Err(TODO) 
    }
}?;
```

2022-11-02 17:30 UTC, pacu approved these changes
utACK

2022-11-02 17:30 UTC, pacu commented on zcash_primitives/CHANGELOG.md
> +  - `Infalliable` an uninhabited error type for conditions where no error can occur.
```suggestion
  - `Infallible` an uninhabited error type for conditions where no error can occur.
```

2022-11-04 00:54 UTC, str4d commented on zcash_primitives/src/sapling.rs
> +    pub fn commitment(&self) -> Node {
Needs documentation.

2022-11-04 01:01 UTC, str4d approved these changes
utACK cdfca848eae42e7b3396da558859695cf36767c3 after changelog updates.

2022-11-04 01:34 UTC, str4d approved these changes
Re-utACK 981d45e9661445ecaef757c497d66af1f249ef3c. Changes over last review are only to documentation.

2022-11-04 01:34 UTC, merged