Implements fmt::Display descriptions for FsBlockDbError
zcash/librustzcash pull request #747
Opened 2022-12-28 19:23 UTC by pacu

Closes #742

This is mainly for FFI Display

2022-12-30 23:14 UTC, nuttycom approved these changes
utACK modulo Clippy fixes.

2022-12-31 18:58 UTC, pacu commented
Clippy fixed. Thanks!

2022-12-31 19:05 UTC, pacu commented
Rustfmt and clippy don't get along. I opened a ticket around this issue

https://github.com/zcash/librustzcash/issues/750

2022-12-31 21:15 UTC, str4d requested changes

2022-12-31 21:15 UTC, str4d commented on zcash_client_sqlite/src/lib.rs
> +            FsBlockDbError::CorruptedData(e) => write!(f, "FsBlockDbError::CorruptedData({})", e),
These are not suitable descriptions for a `Display` impl, as they should be user-meaningful (vs `Debug` impls for which these would be fine). See https://github.com/zcash/librustzcash/blob/125d2bc3d58c543ad58eb53b6c65c0d616688f52/zcash_client_sqlite/src/error.rs#L98-L128 for a (terse but sufficient) example of an error `Display` impl.

2022-12-31 21:15 UTC, str4d commented on zcash_client_backend/src/welding_rig.rs
> +{
Have `rustfmt` take precedence here and leave in the clippy warnings.

2022-12-31 21:15 UTC, str4d commented on zcash_client_sqlite/src/lib.rs
> +    {
Ditto.

2023-01-03 16:31 UTC, str4d requested changes
The code also needs a `cargo fmt`.

2023-01-03 16:31 UTC, str4d commented on zcash_client_sqlite/src/lib.rs
> +            FsBlockDbError::MissingBlockPath(_) => write!(f, "A path to a cached block was provided but it can't be found"),
```suggestion
            FsBlockDbError::MissingBlockPath(block_path) => write!(f, "CompactBlock file expected but not found at {}", block_path.display()),
```

2023-01-03 16:31 UTC, str4d commented on zcash_client_sqlite/src/lib.rs
> +            FsBlockDbError::InvalidBlockstoreRoot(_) => write!(f, "The block storage root provided is invalid"),
```suggestion
            FsBlockDbError::InvalidBlockstoreRoot(fsblockdb_root) => write!(f, "The block storage root {} is not a directory", fsblockdb_root.display()),
```

2023-01-03 16:31 UTC, str4d commented on zcash_client_sqlite/src/lib.rs
> +            FsBlockDbError::InvalidBlockPath(_) => write!(f, "The block path provided is invalid."),
```suggestion
            FsBlockDbError::InvalidBlockPath(block_path) => write!(f, "CompactBlock path {} is not a file", block_path.display()),
```

2023-01-03 18:01 UTC, pacu commented
I fixed `cargo fmt` issues and added @str4d 's

2023-01-04 08:15 UTC, str4d approved these changes
utACK

2023-01-04 08:15 UTC, merged