[#751] add support for rewind_to_height to FsBlockDb
zcash/librustzcash pull request #756
Opened 2023-01-11 23:08 UTC by pacu

Closes #751

2023-01-12 02:40 UTC, nuttycom requested changes
This looks fine apart from the `unwrap`.

2023-01-12 02:40 UTC, nuttycom commented on zcash_client_sqlite/src/chain.rs
> +        .unwrap()
```suggestion
    conn.prepare("DELETE FROM compactblocks_meta WHERE height > ?")?
```

2023-01-14 19:43 UTC, nuttycom commented on zcash_client_sqlite/src/chain.rs
> +    conn.prepare("DELETE FROM compactblocks_meta WHERE height > ?")
```suggestion
    conn.prepare("DELETE FROM compactblocks_meta WHERE height > ?")?
```

2023-01-14 19:44 UTC, nuttycom commented on zcash_client_sqlite/src/chain.rs
> +    conn.prepare("DELETE FROM compactblocks_meta WHERE height > ?")
Missed the question mark (to return the result as an error) rather than `unwrap`.

2023-01-14 19:44 UTC, nuttycom requested changes
Not compiling.

2023-01-19 17:11 UTC, str4d commented
Compilation failure is due to `rustls 0.20.8` bumping its MSRV to 1.57.0 (as a result of its own dependencies bumping MSRV). We only use `rustls` when the `download-params` feature of `zcash_proofs` is enabled; here it is being enabled during testing.

I'll open a separate issue for handling or bumping MSRV.

2023-01-23 15:08 UTC, nuttycom approved these changes
utACK

2023-01-25 03:19 UTC, merged